# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 15, 15, 56, 231174, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
