# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170827_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
